import { DirectoryShell } from "../../components/DirectoryShell"
import { MatchInfoBar } from "../../components/MatchInfoBar"
export function HelloWorldPage() {
  return (
    <DirectoryShell title="Hello World"       subtitle="ggg">
      <MatchInfoBar />
      <section className="grid gap-6 lg:grid-cols-[1.2fr_0.8fr]">
        <p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer efficitur interdum risus, id sagittis neque faucibus sed. Vestibulum aliquam sem orci, et euismod neque placerat et. Mauris gravida nisl erat, eu venenatis magna pretium at. Fusce venenatis velit eget mauris maximus porta. Nulla et nunc enim. Proin vitae pulvinar ligula, sed volutpat est. Cras dolor nunc, congue vitae ex at, efficitur commodo ante. Phasellus aliquam enim non porttitor posuere. Sed imperdiet, massa ut imperdiet consectetur, felis purus pretium sem, id porttitor libero ante et sem. Pellentesque lectus felis, gravida id dapibus sit amet, sodales at felis. Maecenas suscipit luctus aliquet.

Praesent in elit placerat, mattis est sit amet, dignissim massa. Duis sit amet libero sem. Nam pretium faucibus turpis, vel porta velit placerat sed. Donec accumsan scelerisque nulla eget egestas. Phasellus tempor nulla vitae odio ullamcorper porta. Donec tempor semper urna, pulvinar tempus velit blandit in. Phasellus posuere at orci sodales mollis.

Morbi eleifend efficitur diam ac interdum. Maecenas elementum mauris ac neque semper, et placerat est scelerisque. Suspendisse nec condimentum purus. Nam dolor enim, sagittis gravida tortor id, imperdiet tempus dui. Etiam vel mi elementum, vulputate tellus sed, ullamcorper ex. Maecenas consequat erat a massa convallis rutrum. In ac justo vestibulum, ultrices mi at, placerat diam. Maecenas vel dolor enim. Etiam at eros vel elit sodales tincidunt. Donec vitae pharetra ex. Proin ut ornare lectus. Cras bibendum justo vel mi posuere vehicula. Mauris tincidunt consectetur augue ac ultricies. Maecenas sit amet condimentum magna. Nunc lobortis fringilla nunc ut varius. Aenean vehicula eu libero vitae fermentum.

Nunc sed diam est. Suspendisse potenti. Pellentesque et ante metus. Pellentesque eu maximus justo. Nunc ultricies arcu neque, quis fringilla velit interdum sit amet. Praesent vel dictum felis, sed rutrum mauris. Praesent ex nulla, aliquet non iaculis quis, tincidunt nec ipsum. Vestibulum fermentum dignissim nibh eget fermentum. Nullam quam est, lacinia ut mi sed, tempor vehicula elit. Donec a mi est. Pellentesque mollis sit amet ipsum id varius. Vestibulum et augue quis tortor venenatis sollicitudin a at leo. Fusce commodo efficitur gravida. Phasellus nec enim maximus, tincidunt nibh vel, varius turpis. Maecenas vel turpis urna.

Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In et quam sed ligula varius egestas quis quis est. Aenean porttitor vestibulum eros id blandit. Etiam tincidunt commodo rhoncus. Phasellus ut risus vel dolor dapibus feugiat nec quis lorem. Aliquam eu sapien ipsum. Aliquam eget sem pretium, viverra enim non, tincidunt est. Nam aliquam non mi sed dapibus. Sed mauris nulla, laoreet id ornare et, sagittis vel nisi. Cras viverra in nisi vel ultricies. Phasellus sit amet consectetur justo.</p>
<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer efficitur interdum risus, id sagittis neque faucibus sed. Vestibulum aliquam sem orci, et euismod neque placerat et. Mauris gravida nisl erat, eu venenatis magna pretium at. Fusce venenatis velit eget mauris maximus porta. Nulla et nunc enim. Proin vitae pulvinar ligula, sed volutpat est. Cras dolor nunc, congue vitae ex at, efficitur commodo ante. Phasellus aliquam enim non porttitor posuere. Sed imperdiet, massa ut imperdiet consectetur, felis purus pretium sem, id porttitor libero ante et sem. Pellentesque lectus felis, gravida id dapibus sit amet, sodales at felis. Maecenas suscipit luctus aliquet.

Praesent in elit placerat, mattis est sit amet, dignissim massa. Duis sit amet libero sem. Nam pretium faucibus turpis, vel porta velit placerat sed. Donec accumsan scelerisque nulla eget egestas. Phasellus tempor nulla vitae odio ullamcorper porta. Donec tempor semper urna, pulvinar tempus velit blandit in. Phasellus posuere at orci sodales mollis.

Morbi eleifend efficitur diam ac interdum. Maecenas elementum mauris ac neque semper, et placerat est scelerisque. Suspendisse nec condimentum purus. Nam dolor enim, sagittis gravida tortor id, imperdiet tempus dui. Etiam vel mi elementum, vulputate tellus sed, ullamcorper ex. Maecenas consequat erat a massa convallis rutrum. In ac justo vestibulum, ultrices mi at, placerat diam. Maecenas vel dolor enim. Etiam at eros vel elit sodales tincidunt. Donec vitae pharetra ex. Proin ut ornare lectus. Cras bibendum justo vel mi posuere vehicula. Mauris tincidunt consectetur augue ac ultricies. Maecenas sit amet condimentum magna. Nunc lobortis fringilla nunc ut varius. Aenean vehicula eu libero vitae fermentum.

Nunc sed diam est. Suspendisse potenti. Pellentesque et ante metus. Pellentesque eu maximus justo. Nunc ultricies arcu neque, quis fringilla velit interdum sit amet. Praesent vel dictum felis, sed rutrum mauris. Praesent ex nulla, aliquet non iaculis quis, tincidunt nec ipsum. Vestibulum fermentum dignissim nibh eget fermentum. Nullam quam est, lacinia ut mi sed, tempor vehicula elit. Donec a mi est. Pellentesque mollis sit amet ipsum id varius. Vestibulum et augue quis tortor venenatis sollicitudin a at leo. Fusce commodo efficitur gravida. Phasellus nec enim maximus, tincidunt nibh vel, varius turpis. Maecenas vel turpis urna.

Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In et quam sed ligula varius egestas quis quis est. Aenean porttitor vestibulum eros id blandit. Etiam tincidunt commodo rhoncus. Phasellus ut risus vel dolor dapibus feugiat nec quis lorem. Aliquam eu sapien ipsum. Aliquam eget sem pretium, viverra enim non, tincidunt est. Nam aliquam non mi sed dapibus. Sed mauris nulla, laoreet id ornare et, sagittis vel nisi. Cras viverra in nisi vel ultricies. Phasellus sit amet consectetur justo.</p>
<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer efficitur interdum risus, id sagittis neque faucibus sed. Vestibulum aliquam sem orci, et euismod neque placerat et. Mauris gravida nisl erat, eu venenatis magna pretium at. Fusce venenatis velit eget mauris maximus porta. Nulla et nunc enim. Proin vitae pulvinar ligula, sed volutpat est. Cras dolor nunc, congue vitae ex at, efficitur commodo ante. Phasellus aliquam enim non porttitor posuere. Sed imperdiet, massa ut imperdiet consectetur, felis purus pretium sem, id porttitor libero ante et sem. Pellentesque lectus felis, gravida id dapibus sit amet, sodales at felis. Maecenas suscipit luctus aliquet.

Praesent in elit placerat, mattis est sit amet, dignissim massa. Duis sit amet libero sem. Nam pretium faucibus turpis, vel porta velit placerat sed. Donec accumsan scelerisque nulla eget egestas. Phasellus tempor nulla vitae odio ullamcorper porta. Donec tempor semper urna, pulvinar tempus velit blandit in. Phasellus posuere at orci sodales mollis.

Morbi eleifend efficitur diam ac interdum. Maecenas elementum mauris ac neque semper, et placerat est scelerisque. Suspendisse nec condimentum purus. Nam dolor enim, sagittis gravida tortor id, imperdiet tempus dui. Etiam vel mi elementum, vulputate tellus sed, ullamcorper ex. Maecenas consequat erat a massa convallis rutrum. In ac justo vestibulum, ultrices mi at, placerat diam. Maecenas vel dolor enim. Etiam at eros vel elit sodales tincidunt. Donec vitae pharetra ex. Proin ut ornare lectus. Cras bibendum justo vel mi posuere vehicula. Mauris tincidunt consectetur augue ac ultricies. Maecenas sit amet condimentum magna. Nunc lobortis fringilla nunc ut varius. Aenean vehicula eu libero vitae fermentum.

Nunc sed diam est. Suspendisse potenti. Pellentesque et ante metus. Pellentesque eu maximus justo. Nunc ultricies arcu neque, quis fringilla velit interdum sit amet. Praesent vel dictum felis, sed rutrum mauris. Praesent ex nulla, aliquet non iaculis quis, tincidunt nec ipsum. Vestibulum fermentum dignissim nibh eget fermentum. Nullam quam est, lacinia ut mi sed, tempor vehicula elit. Donec a mi est. Pellentesque mollis sit amet ipsum id varius. Vestibulum et augue quis tortor venenatis sollicitudin a at leo. Fusce commodo efficitur gravida. Phasellus nec enim maximus, tincidunt nibh vel, varius turpis. Maecenas vel turpis urna.

Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In et quam sed ligula varius egestas quis quis est. Aenean porttitor vestibulum eros id blandit. Etiam tincidunt commodo rhoncus. Phasellus ut risus vel dolor dapibus feugiat nec quis lorem. Aliquam eu sapien ipsum. Aliquam eget sem pretium, viverra enim non, tincidunt est. Nam aliquam non mi sed dapibus. Sed mauris nulla, laoreet id ornare et, sagittis vel nisi. Cras viverra in nisi vel ultricies. Phasellus sit amet consectetur justo.</p>
<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer efficitur interdum risus, id sagittis neque faucibus sed. Vestibulum aliquam sem orci, et euismod neque placerat et. Mauris gravida nisl erat, eu venenatis magna pretium at. Fusce venenatis velit eget mauris maximus porta. Nulla et nunc enim. Proin vitae pulvinar ligula, sed volutpat est. Cras dolor nunc, congue vitae ex at, efficitur commodo ante. Phasellus aliquam enim non porttitor posuere. Sed imperdiet, massa ut imperdiet consectetur, felis purus pretium sem, id porttitor libero ante et sem. Pellentesque lectus felis, gravida id dapibus sit amet, sodales at felis. Maecenas suscipit luctus aliquet.

Praesent in elit placerat, mattis est sit amet, dignissim massa. Duis sit amet libero sem. Nam pretium faucibus turpis, vel porta velit placerat sed. Donec accumsan scelerisque nulla eget egestas. Phasellus tempor nulla vitae odio ullamcorper porta. Donec tempor semper urna, pulvinar tempus velit blandit in. Phasellus posuere at orci sodales mollis.

Morbi eleifend efficitur diam ac interdum. Maecenas elementum mauris ac neque semper, et placerat est scelerisque. Suspendisse nec condimentum purus. Nam dolor enim, sagittis gravida tortor id, imperdiet tempus dui. Etiam vel mi elementum, vulputate tellus sed, ullamcorper ex. Maecenas consequat erat a massa convallis rutrum. In ac justo vestibulum, ultrices mi at, placerat diam. Maecenas vel dolor enim. Etiam at eros vel elit sodales tincidunt. Donec vitae pharetra ex. Proin ut ornare lectus. Cras bibendum justo vel mi posuere vehicula. Mauris tincidunt consectetur augue ac ultricies. Maecenas sit amet condimentum magna. Nunc lobortis fringilla nunc ut varius. Aenean vehicula eu libero vitae fermentum.

Nunc sed diam est. Suspendisse potenti. Pellentesque et ante metus. Pellentesque eu maximus justo. Nunc ultricies arcu neque, quis fringilla velit interdum sit amet. Praesent vel dictum felis, sed rutrum mauris. Praesent ex nulla, aliquet non iaculis quis, tincidunt nec ipsum. Vestibulum fermentum dignissim nibh eget fermentum. Nullam quam est, lacinia ut mi sed, tempor vehicula elit. Donec a mi est. Pellentesque mollis sit amet ipsum id varius. Vestibulum et augue quis tortor venenatis sollicitudin a at leo. Fusce commodo efficitur gravida. Phasellus nec enim maximus, tincidunt nibh vel, varius turpis. Maecenas vel turpis urna.

Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In et quam sed ligula varius egestas quis quis est. Aenean porttitor vestibulum eros id blandit. Etiam tincidunt commodo rhoncus. Phasellus ut risus vel dolor dapibus feugiat nec quis lorem. Aliquam eu sapien ipsum. Aliquam eget sem pretium, viverra enim non, tincidunt est. Nam aliquam non mi sed dapibus. Sed mauris nulla, laoreet id ornare et, sagittis vel nisi. Cras viverra in nisi vel ultricies. Phasellus sit amet consectetur justo.</p>
      </section>
      
    </DirectoryShell>
  );
}